export const ENV = {
  appId: process.env.VITE_APP_ID ?? "my-custom-panel-shop",
  cookieSecret: process.env.JWT_SECRET ?? "replace-with-secure-random-string-at-least-32-chars",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  adminPassword: process.env.ADMIN_PASSWORD ?? "admin_password_change_me",
  smtpHost: process.env.SMTP_HOST ?? "smtpout.secureserver.net",
  smtpPort: parseInt(process.env.SMTP_PORT ?? "465"),
  smtpUser: process.env.SMTP_USER ?? "admin@casperspaintworks.com.au",
  smtpPass: process.env.SMTP_PASS ?? "",
};
